# Этот файл нужен для быстрой развертки сервера в TGS
# Конечно в данный момент он не нужен, так как сервер уже развёрнут
# Но пригодится в будующем когда хост санька помрёт

version: 1
byond: "515.1647"
static_files:
  - name: config
    populate: true
  - name: data
linux_scripts:
  PreCompile.sh: tools/tgs_scripts/PreCompile.sh
  WatchdogLaunch.sh: tools/tgs_scripts/WatchdogLaunch.sh
  InstallDeps.sh: tools/tgs_scripts/InstallDeps.sh
windows_scripts:
  PreCompile.bat: tools/tgs_scripts/PreCompile.bat
security: Trusted
